  name: devops_CD

  on:
    # push:
    #   branches:
    #     - main
    pull_request:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
      
        - name: Write env file
          run:
              echo "${{ secrets.ENV_FILE }}" > .env

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
      
        - name: Log in to ghcr.io
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.PAT }}
      
        - name: Build and Push Docker image
          run: |
            docker compose build
            docker compose push
        
        - name: Copy configuration files
          uses: appleboy/scp-action@v0.1.0
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            source: "docker-compose.yml"
            target: "/root/devops"

        - name: Deploy
          uses: appleboy/ssh-action@v0.1.8
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
              cd /root
              echo "${{ secrets.ENV_FILE }}" > .env.production
              echo "${{ secrets.ENV_FILE }}" > .env
              chmod 644 .env.production
              chmod 644 .env

              ghcrback
              
              docker compose pull
              docker compose down --remove-orphans
              docker container prune
              docker compose up -d
              docker image prune -f

      